[build]
  command = "cd client && npm install --legacy-peer-deps && npm run build"
  publish = "client/build"
  functions = "server"

[[redirects]]
  from = "/api/*"
  to = "https://your-netlify-app-name.netlify.app/api/:splat"
  status = 200

[build.environment]
  NODE_ENV = "production"

[dev]
  command = "cd server && npm install && node --watch server.js"
  functions = "server"
