[build]
  command = "cd client && npm install && npm run build"
  publish = "client/build"

  # Добавьте настройки для сервера
  command = "npm install && node server.js"
  functions = "server"

[[redirects]]
  from = "/api/*"
  to = "http://localhost:3001/:splat"
  status = 200

[build.environment]
  NODE_ENV = "production"

[dev]
  command = "cd server && npm install && node --watch server.js"
  functions = "server"
