[build]
  command = "cd client && npm install && npm run build"
  publish = "client/build"

[[redirects]]
  from = "/api/*"
  to = "http://localhost:3001/:splat"
  status = 200

[build.environment]
  NODE_ENV = "production"

[[build]]
  command = "npm install && node server.js"  # Команда для запуска сервера
  functions = "server"  # Папка с серверными функциями

[dev]
  command = "cd server && npm install && node --watch server.js"
  functions = "server"
